### ISSUE TITLE
datetime-mixin - date operations

### ISSUE THREAD

**Issue by a8775** [fooloomanzoo/property-mixins#2]
In the `datetime-mixin` there is something like:
```
          ...
           if (isNaN(d)) {
            d = new Date();
          }
          d.setMilliseconds(milliseconds || 0);
          d.setSeconds(seconds || 0);
          d.setMinutes(minutes || 0);
          d.setHours(hours || 0);
          if (day !== undefined) {
            d.setDate(day);
          }
          if (month !== undefined) {
            d.setMonth(month - 1);
          }
          ...
 ```

Above calculations are not working as expected under iOS Chrome version 63.0.3239.132, eg:

If I want to set `2018-01-29` and today is `2018-02-05`
first the date is initialized with new Date() to current date. After that the day part is updated to be equal `29` but due to `Date` nature `d` object is actually set to be `2018-03-01`, and in the end the month part is set. The final value of `d` is equal `2018-01-01`.

The fast fix is to change the order `d.setMonth()` and than `d.setDay()`.

**Comment by a8775** [comment]
Few minutes ago I saw similar problem in `_datetimeChanged()` but now it's fixed, thanks :)

**Comment by fooloomanzoo** [comment]
I changed the order
